version: '2'
services:
  api:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.5
    ports:
      - '27018:27018'
    command: mongod --port 27018 --bind_ip_all
